name: GitHub Actions Version Updater

on:
  push:
  pull_request:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.5.6
        with:
          commit_message: "ci(action): bump GitHub Actions"
          pull_request_title: "ci(action): bump GitHub Actions"
          token: ${{ github.token }}
