name: GitHub Actions Version Updater

on:
  push:
  pull_request:

jobs:
  bump:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@main
        with:
          commit_message: "ci(action): bump GitHub Actions"
          pull_request_title: "ci(action): bump GitHub Actions"
          ignore: '["saadmk11/github-actions-version-updater@main"]'
          token: ${{ github.token }}
